name: Test

on:
  push:
  pull_request:

jobs:
  powershell-51:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Windows PowerShell 5.1 tests
        shell: powershell
        run: .\tests\Run-Tests.ps1
